# Lecture 11

# NumPy Basics

## Week 4 Wednesday

## Miles Chen, PhD

Based on Python Data Science Handbook by Jake VanderPlas

## ALWAYS do: `import numpy as np`
This is a convention that everyone follows. If you do not do this, other people will have a hard time reading your code

In [ ]:
import numpy as np

In [ ]:
np.__version__

## Numpy arrays
- this is what is brought in when you import numpy
- like lists, arrays are mutable
- unlike lists, arrays can only contain data of the same data type

-basically anything data oriented in python requires use of numpy 
departure from base python (and main textbook!)

## Making Arrays
- direct creation with `np.array()`
- Create a list with square brackets, and put that inside `np.array()`

In [ ]:
np.array([1,2,3,4])

In [ ]:
array_1 = np.array([1,3,5])

print(array_1) # printing an array appears different from the array([]) in ipython and has no commas, just spaces

In [ ]:
print([1,2,3]) # a printed list has commas

A printed array has no commas. A printed list has commas.

In [ ]:
type(array_1)

In the following code cells, I'll sometimes just produce the array directly and sometimes I will call print on the array. Get used to seeing both kinds of output.

### Arrays in Higher dimensions

If you provide a list of lists, you can create a multi-dimensional array. (Like a matrix)

In [ ]:
d = np.array( [ [1,2,3] , [4,5,6] ] ) 
print(d)

When you print a multidimensional array, the number of opening square brackets is the number of dimensions. The above array is 2 dimensional.

but if the dimensions don't match, you'll get an error.

In [ ]:
e = np.array([ [1,2,3],[4,5] ])
print(e)

## Other ways to make arrays

In [ ]:
print(np.zeros(5)) # makes an array of 0s. similar to rep(0, 5)

In [ ]:
print(np.zeros(5, dtype = int))  # default is to make floats, you can specify ints

In [ ]:
print(np.zeros((2,4)))  # give dimensions as a tuple: makes an array 2x4

In [ ]:
print(np.zeros((2,3,4))) # 3 dimensional array 2 x 3 x 4... 
# notice the order of creation: 2 'sheets' of 3 rows by 4 columns

In [ ]:
np.zeros((2,3,4,5))
# make 2 'blocks', each with 3 'sheets', of 4 rows, and 5 columns

In addition to `np.zeros` there is `np.ones` and `np.full` which can create new arrays.

In [ ]:
print(np.ones(5))  # similar, but inserts ones

In [ ]:
print(np.full((2,3), 1.2))# similar, but you specify one value that gets repeated
print("")
print(np.full((4,3), 4.11))

## Making arrays of random numbers
numpy uses the Mersenne Twister
- Create a generator with `np.random.default_rng()`

In [ ]:
# create a new random number generator with a fixed seed for reproducibility
rng = np.random.default_rng(seed=1)

In [ ]:
print(rng.random(5))  # random.random for random values on the interval [0,1)

In [ ]:
rng.standard_normal(5)
# random.randn for random normal from standard normal
# this command will produce 5 values

In [ ]:
rng.standard_normal((5, 2)) # you can provide a tuple of dimensions

In [ ]:
rng.normal(10, 3, (2, 4))
# random.randn for random normal from normal with mean 10 and sd 3
# arranged in a 2 x 4 matrix

In [ ]:
rng.integers(0, 10, 20) 
# select random integers from 0 inclusive to 10 exclusive
# and return 20 values

In [ ]:
# simulate dice rolls
rng.integers(1,7, 50)

More random generation at: https://numpy.org/doc/stable/reference/random/index.html

## Array sequences
make sequences with

- `np.arange(start, stop, step)`  
-  makes an **a**rray **range** from start (inclusive) to stop (exclusive), by step

In [ ]:
range(0, 10, 2) # range object in regular python

In [ ]:
print(list(range(0, 10, 2)))

list(range(0,10,3))

In [ ]:
np.arange(0, 10, 2)  # numpy's arange function

In [ ]:
np.array(range(0,10,2)) # equivalent 'manual' creation

In [ ]:
np.arange(0, 100, 5)

In [ ]:
np.arange(20) # quickest

- `np.linspace(start, stop, num)`
- makes an array of **lin**ear **space**d values beginning with start, ending with stop (inclusive), with a length of num

In [ ]:
np.linspace(0, 100, 11)

In [ ]:
np.linspace(0, 100, 10)

In [ ]:
np.linspace(0, 100, 10, endpoint = False)  
# optional parameter endpoint to exclude the stop value

In [ ]:
np.linspace(0, 100, 9, endpoint = False) 
# if you use the endpoint argument, the last number in the array will depend on the output length

### Upcasting (Coercion in R and Implicit Casting in C++)

If you mix data types in an array, the values of the more restrictive types will get upcast to the value of the less restrictive type.

In [ ]:
b = np.array([1, 2, 3.0, False, True])
print(b) # the 3.0 is a float and will upcast (coerce) other values to floats

In [ ]:
c = np.array([1, 2, "3", True, False]) # upcast (coerced) to strings
print(c)

# Array Attributes
- `array.ndim` for number of dimensions
- `array.shape` for the size of each dimension
- `array.dtype` for the data type 

In [ ]:
x = np.ones((3,4))
print(x)

In [ ]:
x.ndim

In [ ]:
x.shape

In [ ]:
x.dtype

In [ ]:
y = np.arange(0, 12, 1)
print(y)

In [ ]:
y.ndim

In [ ]:
y.shape # a one dimensional array. Note that there's no second dimension.

## Reshaping Arrays

- `np.reshape(array, [new shape])` returns a new array that is reshaped
    - you can also use the method `array.reshape(shape)`
    *these will not affect the oriignal array
- `array.T` is the transpose method, but leaves the original array unaffected


In [93]:
j = np.arange(0,12,1)
print(j) # j is one dimensional

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [94]:
k = np.reshape(j, (3,4))  # note that it fills row-wise unlike R
print(k)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [95]:
j # j is left unchanged

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [96]:
j.reshape(4,3)  # you can also call the method reshape() on the array j

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [97]:
j # j is left unchanged here as well

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [98]:
print(k)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [99]:
print(k.T)  # the transpose of k

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [100]:
print(k) # calling k.T does not modify the original k array

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [101]:
# can combine the above methods and steps into one:
l = np.arange(0,12,1).reshape((3,4)).T
# create a-range >> reshape >> transpose
print(l)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [102]:
j

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [103]:
j.reshape((3, -1))  # using -1 for a dimension will ask python to figure out the number to use for that dimension

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [104]:
j.reshape((-1, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
j.reshape((2, -1, 2)) # two sheets, unknown number of rows, 2 columns

In [111]:
y = np.arange(0,12, 1)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [112]:
y.shape

(12,)

In [105]:
print(y.T) # the transpose of a one dimensional array doesn't suddenly give it a second dimension

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
y.T.shape

In [106]:
z = np.reshape(y, (1,12)) # the array now has two dimensions
print(z)

[[ 0  1  2  3  4  5  6  7  8  9 10 11]]


In [107]:
z.shape

(1, 12)

In [108]:
print(z.T)  # with two dimensions, the transpose become a column

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]


In [109]:
z.T.shape

(12, 1)

- `ravel()` returns a **view** when it can.
- `flatten()` **always copies**.

In [113]:
C = np.arange(6).reshape(2,3)
C

array([[0, 1, 2],
       [3, 4, 5]])

In [114]:

C_unraveled = C.ravel()      # view
C_unraveled


array([0, 1, 2, 3, 4, 5])

In [115]:
C_flattened = C.flatten()    # copy
C_flattened

array([0, 1, 2, 3, 4, 5])

In [116]:
C += 1
C

array([[1, 2, 3],
       [4, 5, 6]])

In [117]:
C_unraveled

array([1, 2, 3, 4, 5, 6])

In [118]:
C_flattened


array([0, 1, 2, 3, 4, 5])

# Subsetting and Slicing Arrays
- very similar to subsetting and slicing lists

In [119]:
y = np.arange(0,12, 1)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [120]:
y[4]

np.int64(4)

In [121]:
y.shape

(12,)

In [122]:
y[4:6]

array([4, 5])

you can slice with a second colon. The array gets subset with `array[start:stop:step]`

In [123]:
y[1:8:3]

array([1, 4, 7])

In [124]:
np.arange(100)[:100:2] # to get even values

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [125]:
np.arange(0,100,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

Subsetting and slicing higher dimensional arrays is similar, and uses a comma to separate subsetting instructions for each dimension.

In [126]:
z = np.reshape(y, [3,4])
print(z)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [127]:
print(z[1,2]) # returns what is at row index 1, col index 2

6


In [128]:
type(z[1,2]) # with only one value, the type is the integer. It is no longer an array.

numpy.int64

In [129]:
print(z)
z[0:2, 0:2] # note the type remains a numpy array

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[0, 1],
       [4, 5]])

In [130]:
print(z[2, :]) # returns row at index 2

[ 8  9 10 11]


In [131]:
print(z[2, ])

[ 8  9 10 11]


In [132]:
z[2, :].shape  # the shape is one dimensional

(4,)

In [133]:
print(z[:,2]) # returns column at index 2

[ 2  6 10]


In [134]:
z[:,2].shape # shape is one dimensional

(3,)

#### Slices of numpy arrays are view objects, and automatically update if the original array is updated.

In [135]:
z = np.arange(12).reshape([3,4])
print(z)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [136]:
# we use numpy array slicing to create z_sub, the top left corner of z
z_sub = z[:2, :2]
print(z_sub)

[[0 1]
 [4 5]]


In [137]:
# I modify the first element of z to be 99.
z[0,0] = 99

In [138]:
print(z_sub)  # z_sub is updated, even though we never redefined it

[[99  1]
 [ 4  5]]


In [139]:
z

array([[99,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [140]:
z = np.arange(15).reshape([3,5]) # here z gets redefined to an entirely new object
# we are not modifying the object that used to be called z
# we created a new object, and the name z now points to the new object

In [142]:
z

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [141]:
print(z_sub)  # the view z_sub still points to the object formerly known as z, which was not modified 

[[99  1]
 [ 4  5]]


## If you want a copy that will not update if the original is updated, use `array.copy()`

In [143]:
print(z)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [144]:
z_sub_copy = z[:2, :2].copy()
print(z_sub_copy)

[[0 1]
 [5 6]]


In [145]:
z[0,0] = 55 # modify the first element of z

In [146]:
print(z_sub_copy) # the copy remains unaffected by the change

[[0 1]
 [5 6]]


In [147]:
print(z)

[[55  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


Modifying the view object modifies the underlying array

In [148]:
z = np.arange(12).reshape((3,4))
print(z)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [149]:
view = z[:2,:2]

In [150]:
view[0,0] = 99

In [151]:
view

array([[99,  1],
       [ 4,  5]])

In [152]:
z

array([[99,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [153]:
type(view) # view objects themselves are arrays and have all the same methods and attributes

numpy.ndarray

In [154]:
view.T

array([[99,  4],
       [ 1,  5]])

In [155]:
view.T.reshape((4,))

array([99,  4,  1,  5])

In [156]:
view # attributes like .T do not affect the orignal array

array([[99,  1],
       [ 4,  5]])

In [157]:
view[0,0] = 1000

In [158]:
z

array([[1000,    1,    2,    3],
       [   4,    5,    6,    7],
       [   8,    9,   10,   11]])